### ISSUE TITLE
File "pdpublic.h" is missing from the h directory

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/os2tk45#1]
At one point in time Scott Garfinkle made available file "pdpublic.h" which contains the interface definitions for the "DosDumpProcess" API function. This became part of the eCS toolkit.

**Comment by dmik** [comment]
@lerdmann What you see here is taken from the eCS 1.1 Media Refresh OS2TK45 folder on the second CD. Was there a newer eCS release of OS2TK45? I'm not aware of it (and don't have it). If you point me me to any newer distribution, I will update this repository (and the RPMs) with it.

**Comment by lerdmann** [comment]
I just checked: the eCS 2.1 disc 2 contained an updated toolkit that also contained the "pdpublic.h" file.
Beware for later eCS toolkits, they accidentally additionally replaced file "acb.h" with the contents of file "pdpublic.h". However, this problem did not exist with the toolkit of eCS 2.1. However you might want to diff ...

**Comment by SilvanScherrer** [comment]
fixed with the above commit
